;; -*- mode: eask; lexical-binding: t -*-

(package "evil-escape-hook"
         "1.0.0"
         "Evil Escape, but with a hook and cleaned up")

(website-url "https://github.com/jgrey4296/evil-escape-hook")
(keywords "convenience" "editing" "evil")

(package-file "evil-escape-hook.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.2")
(depends-on "evil")
(depends-on "cl-lib")
(depends-on "dash")
